# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on: #[push pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
            python-version: "3.10.8"
      - uses: extractions/setup-just@v1
    
      - name: Install Prerequisites
        run: pip3 install -r requirements.txt

      - name: format/lint check
        run: just check
      
      #- uses: codecov/codecov-action@v3
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    verbose: true